[package]
name = "url_shortener"
version = "0.1.0"
edition = "2018"

[dependencies]
actix-web = "4.0"
rusqlite = "0.25"
sha2 = "0.9"
base64 = "0.12"
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15.0"
sqlx = { version = "0.5", features = ["sqlite", "runtime-actix-native-tls"] }
